import { UrbanProjectCustomCreationStep } from "../urban-project/creationSteps";
import { InformationalStep, StepAnswers } from "./steps.types";

const INFORMATIONAL_STEPS_SET = new Set<InformationalStep>([
  "URBAN_PROJECT_SPACES_CATEGORIES_INTRODUCTION",
  "URBAN_PROJECT_SPACES_DEVELOPMENT_PLAN_INTRODUCTION",
  "URBAN_PROJECT_GREEN_SPACES_INTRODUCTION",
  "URBAN_PROJECT_RESIDENTIAL_AND_ACTIVITY_SPACES_INTRODUCTION",
  "URBAN_PROJECT_PUBLIC_SPACES_INTRODUCTION",
  "URBAN_PROJECT_SPACES_SOILS_SUMMARY",
  "URBAN_PROJECT_SOILS_CARBON_SUMMARY",
  "URBAN_PROJECT_SOILS_DECONTAMINATION_INTRODUCTION",
  "URBAN_PROJECT_BUILDINGS_INTRODUCTION",
  "URBAN_PROJECT_BUILDINGS_USE_INTRODUCTION",
  "URBAN_PROJECT_STAKEHOLDERS_INTRODUCTION",
  "URBAN_PROJECT_SITE_RESALE_INTRODUCTION",
  "URBAN_PROJECT_EXPENSES_INTRODUCTION",
  "URBAN_PROJECT_REVENUE_INTRODUCTION",
  "URBAN_PROJECT_SCHEDULE_INTRODUCTION",
  "URBAN_PROJECT_FINAL_SUMMARY",
]);

export const isInformationalStep = (
  stepId: UrbanProjectCustomCreationStep,
): stepId is InformationalStep => {
  return INFORMATIONAL_STEPS_SET.has(stepId as InformationalStep);
};

const ANSWER_STEPS_SET = new Set<keyof StepAnswers>([
  "URBAN_PROJECT_SPACES_CATEGORIES_SELECTION",
  "URBAN_PROJECT_SPACES_CATEGORIES_SURFACE_AREA",
  "URBAN_PROJECT_GREEN_SPACES_SURFACE_AREA_DISTRIBUTION",
  "URBAN_PROJECT_RESIDENTIAL_AND_ACTIVITY_SPACES_DISTRIBUTION",
  "URBAN_PROJECT_PUBLIC_SPACES_DISTRIBUTION",
  "URBAN_PROJECT_SOILS_DECONTAMINATION_SELECTION",
  "URBAN_PROJECT_SOILS_DECONTAMINATION_SURFACE_AREA",
  "URBAN_PROJECT_BUILDINGS_FLOOR_SURFACE_AREA",
  "URBAN_PROJECT_BUILDINGS_USE_SURFACE_AREA_DISTRIBUTION",
  "URBAN_PROJECT_STAKEHOLDERS_PROJECT_DEVELOPER",
  "URBAN_PROJECT_STAKEHOLDERS_REINSTATEMENT_CONTRACT_OWNER",
  "URBAN_PROJECT_SITE_RESALE_SELECTION",
  "URBAN_PROJECT_BUILDINGS_RESALE_SELECTION",
  "URBAN_PROJECT_EXPENSES_SITE_PURCHASE_AMOUNTS",
  "URBAN_PROJECT_EXPENSES_REINSTATEMENT",
  "URBAN_PROJECT_EXPENSES_INSTALLATION",
  "URBAN_PROJECT_EXPENSES_PROJECTED_BUILDINGS_OPERATING_EXPENSES",
  "URBAN_PROJECT_REVENUE_EXPECTED_SITE_RESALE",
  "URBAN_PROJECT_REVENUE_BUILDINGS_RESALE",
  "URBAN_PROJECT_REVENUE_BUILDINGS_OPERATIONS_YEARLY_REVENUES",
  "URBAN_PROJECT_REVENUE_FINANCIAL_ASSISTANCE",
  "URBAN_PROJECT_SCHEDULE_PROJECTION",
  "URBAN_PROJECT_NAMING",
  "URBAN_PROJECT_PROJECT_PHASE",
]);

export const isAnwersStep = (
  stepId: UrbanProjectCustomCreationStep,
): stepId is keyof StepAnswers => {
  return ANSWER_STEPS_SET.has(stepId as keyof StepAnswers);
};
